CREATE DATABASE [SuperEuro]
GO
USE [SuperEuro]
GO
/****** Object:  Table [dbo].[game]    Script Date: 15/12/2021 19:55:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[game](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[date] [datetime] NULL,
	[type] [nvarchar](50) NULL,
	[score] [int] NULL,
 CONSTRAINT [PK_party] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[game_stats]    Script Date: 15/12/2021 19:55:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[game_stats](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_user] [int] NOT NULL,
	[id_game] [int] NOT NULL,
	[id_question] [int] NOT NULL,
	[answer] [nvarchar](50) NULL,
	[date] [datetime] NULL,
 CONSTRAINT [PK_game_stats] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[question]    Script Date: 15/12/2021 19:55:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[question](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_theme] [int] NOT NULL,
	[difficulty] [int] NOT NULL,
	[question] [nvarchar](255) NULL,
	[image] [nvarchar](255) NULL,
	[value] [bigint] NULL,
	[texteR1] [nvarchar](50) NULL,
	[texteR2] [nvarchar](50) NULL,
	[texteR3] [nvarchar](50) NULL,
	[correct_answer] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[theme]    Script Date: 15/12/2021 19:55:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[theme](
	[id] [int] NOT NULL,
	[val] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[utilisateur]    Script Date: 15/12/2021 19:55:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[utilisateur](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](100) NULL,
	[motdepasse] [varchar](100) NULL,
	[role] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[question] ON 

INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (1, 1, 1, N'Le mot « cash » désigne ?', NULL, 1, N'Des pièces et des billets', N'Un chanteur', N'Une cachette', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (2, 1, 1, N'Que signifie « time is money » en anglais ?', NULL, 1, N'Le temps c’est de l’argent', N'Le temps manque d’argent', N'L’avenir manque de temps', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (3, 1, 1, N'Comment dit-on « payer » en anglais ? ', NULL, 1, N'To pray', N'To pay', N'To say', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (4, 1, 1, N'Comment dit-on « acheter » en anglais ?', NULL, 1, N'To buy', N'To try', N'Shopping', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (5, 1, 1, N'Comment dit-on « impôt » en anglais ?', NULL, 1, N'Trade', N'Rate', N'Tax', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (6, 1, 1, N'Comment dit-on « rabais » en anglais ?', NULL, 1, N'Discount', N'Loss', N'More', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (7, 1, 1, N'Que signifie « coin » ?', NULL, 1, N'Canard', N'Recoin', N'Pièce de monnaie', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (8, 1, 1, N'Comment dit-on « or » en anglais ?', NULL, 1, N'Silver', N'Gold', N'Copper', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (9, 1, 1, N'Comment dit-on « gagner » en anglais ?', NULL, 1, N'To add', N'To win', N'To grow', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (10, 1, 1, N'Que signifie « half » ?', NULL, 1, N'Tiers provisionnel', N'Moitié', N'Veau d''or', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (11, 1, 1, N'Que signifie « cheap » ?', NULL, 1, N'Une pomme de terre frite', N'Un mouton', N'Pas cher', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (12, 1, 1, N'Que signifie « expensive » ?', NULL, 1, N'Parlant beaucoup', N'Qui se dilate', N'Cher', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (13, 1, 1, N'Que signifie « enough » ?', NULL, 1, N'Encore', N'Trop', N'Assez', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (14, 1, 1, N'Que signifie "businessman" ?', NULL, 1, N'Homme d''affaires', N'Homme pressé', N'Personne qui vend des contrefaçons', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (15, 1, 1, N'Que signifie « banker » ?', NULL, 1, N'Un banquier', N'Un banc', N'Une banque', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (16, 1, 2, N'En finance, le mot « account »  désigne ?', NULL, 2, N'Un compte', N'Une histoire fantastique', N'Un titre de noblesse', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (17, 1, 2, N'Le mot « note» est utilisé pour désigner ?', NULL, 2, N'Un banquier', N'Un billet', N'Une carte bancaire', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (18, 1, 2, N'Que signifie « to purchase » ?', NULL, 2, N'Acheter', N'Pourchasser', N'Vendre', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (19, 1, 2, N'Comment dit-on « carte bancaire » en anglais ?', NULL, 2, N'Green card', N'Bank card', N'Cash card', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (20, 1, 2, N'Que signifie « sales » sur une vitrine ?', NULL, 2, N'Soldes', N'A laver', N'Grande terrasse à l''arrière', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (21, 1, 2, N'Comment dit-on « la Bourse » en anglais ?', NULL, 2, N'Stock Exchange', N'Stonehenge', N'Borough Market', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (22, 1, 2, N'Que signifie «trader » ?', NULL, 2, N'Un vagabond', N'Un caissier', N'Un opérateur sur les marchés financiers', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (23, 1, 2, N'Que signifie « tip » ?', NULL, 2, N'Pourboire', N'Mannequin', N'Robinet', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (24, 1, 2, N'Comment dit-on « perte » en anglais ?', NULL, 2, N'Hole', N'Loss', N'Hide', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (25, 1, 2, N'Comment se nomme la monnaie anglaise ?', NULL, 2, N'Lettuce', N'Pound', N'Inch', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (26, 1, 2, N'Comment dit-on « cinq cent vingt trois » en anglais ?', NULL, 2, N'Seven hundred and eighty nine', N'Five hundred and twenty three', N'Four thousand and thirty two', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (27, 1, 2, N'Comment dit-on "sans taxes" ?', NULL, 2, N'Bargain', N'Duty-free', N'Cashless', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (28, 1, 3, N'Que signifie « saving money »?', NULL, 3, N'Sauver quelqu’un', N'Épargner de l’argent', N'Trouver de l’argent', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (29, 1, 3, N'Que signifie « loan » ?', NULL, 3, N'Un prêt', N'Un porte-monnaie', N'Un logement', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (30, 1, 3, N'Que signifie « expenses » ?', NULL, 3, N'Espèces', N'Dépenses', N'Achat', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (31, 1, 3, N'Que signifie « rate » ?', NULL, 3, N'Rate', N'Taux', N'Manquer', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (32, 1, 3, N'Que signifie « gap » ?', NULL, 3, N'Casquette', N'Gaz de schiste', N'Ecart', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (33, 1, 3, N'Que signifie « bid » ?', NULL, 3, N'Echec, raté', N'Enchère, offre', N'Oiseau', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (34, 1, 3, N'Comment dit-on « financement participatif » en anglais ?', NULL, 3, N'Merger', N'Crowdfunding', N'Commonwealth', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (35, 1, 3, N'Comment dit-on « virement » en anglais ?', NULL, 3, N'Debit', N'Turnround', N'Transfer', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (36, 1, 3, N'A Londres, qu''est-ce qu''un  « ATM » ?', NULL, 3, N'La monnaie galloise', N'Un placement sûr', N'Un distributeur de billets', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (37, 1, 3, N'Que signifie « fees » ?', NULL, 3, N'Les frais ', N'Les glaces', N'Les fées', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (38, 1, 3, N'Comment dit-on « un montant en chiffres » en anglais ?', NULL, 3, N'Amount in full', N'Amount in figures', N'Amount in code', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (39, 1, 3, N'Que signifie «customs » ?', NULL, 3, N'La douane', N'Les habits', N'La corpulence', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (40, 1, 3, N'Comment dit-on « tirelire » en anglais ?', NULL, 3, N'Sparing bank', N'Piggy bank', N'Saving bank', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (41, 1, 3, N'Comment dit-on « spéculer / parier » en anglais ?', NULL, 3, N'To paddle', N'To gamble', N'To ramble', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (42, 1, 3, N'Que signifie « bank clerk » ?', NULL, 3, N'Un(e) employé(e) de banque', N'Une personne dont la banque a clôturé le compte', N'Un chinchilla', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (43, 1, 3, N'Comment dit-on « retirer de l''argent » en anglais ?', NULL, 3, N'To keep the change', N'To withdraw money', N'To change money', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (44, 2, 1, N'Parmi ces éléments, lequel est une dépense ?', NULL, 1, N'L''argent reçu pour un anniversaire', N'L''argent de poche', N'L''achat d’un pantalon', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (45, 2, 1, N'Qu’est-ce qu’un virement ?', NULL, 1, N'Un transfert d’argent d’un compte à un autre', N'Un licenciement', N'Un demi-tour', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (46, 2, 1, N'Qu’est-ce qu’un Livret A ?', NULL, 1, N'Un prêt d’argent', N'Un produit d’épargne', N'Un livre sur l''argent', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (47, 2, 1, N'Une carte bancaire est ?', NULL, 1, N'Un moyen de paiement', N'Un moyen de transport', N'Un moyen de pression', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (48, 2, 1, N'Quelle est la monnaie des États-Unis ? ', NULL, 1, N'Le dollar', N'L''euro', N'La livre', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (49, 2, 1, N'Un distributeur automatique permet de ?', NULL, 1, N'Retirer de l’argent sous forme de billets', N'Payer ses impôts', N'Faire un don', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (50, 2, 1, N'Qu''est-ce que le yen ?', NULL, 1, N'Un animal africain', N'Un jeu de dés', N'La monnaie du Japon', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (51, 2, 1, N'Être à découvert signifie ?', NULL, 1, N'Avoir vendu ses vêtements', N'Avoir dépensé plus d’argent qu’on n’en possède', N'S’être fait prendre à voler de l’argent', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (52, 2, 2, N'Une somme d’argent empruntée est  ?', NULL, 2, N'Une dette', N'Un intérêt', N'Un don', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (53, 2, 2, N'La Banque de France est ?', NULL, 2, N'La banque de l’équipe de France', N'La banque centrale française', N'La banque des présidents français', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (54, 2, 2, N'La Bourse est ?', NULL, 2, N'Un porte-monnaie', N'Un lieu d’échanges de produits financiers', N'Un porte-bonheur', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (55, 2, 2, N'Le patrimoine désigne ?', NULL, 2, N'La patrie des moines tibétains', N'Les biens détenus par l’État', N'L’ensemble des biens d’une personne', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (56, 2, 2, N'La monnaie utilisée dans un autre pays est appelée ?', NULL, 2, N'Un slogan', N'Un jingle', N'Une devise', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (57, 2, 2, N'Qu''est ce que le rouble ?', NULL, 2, N'Une personne rusée', N'La monnaie russe', N'Une multiplication par 1,5', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (59, 2, 2, N'En matière monétaire, qu''est-ce qu''un napoléon ?', NULL, 2, N'Un faux monnayeur', N'Le libellé du 1er billet de banque', N'Une pièce en or', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (60, 2, 2, N'Que fait un usurier ?', NULL, 2, N'Un prêteur à un taux exagéré', N'Un testeur de produits', N'Un forgeron au XVIème siècle', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (61, 2, 2, N'Un financier est un gâteau mais aussi ?', NULL, 2, N'Un bateau', N'Un artificier dans l''armée', N'Un professionnel de la Bourse', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (62, 2, 2, N'Qu''est-ce que Wall-Street ?', NULL, 2, N'La rue de la mode à New-York', N'La Bourse américaine', N'Le surnom de l''ex-mur de Berlin', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (63, 2, 2, N'Un relevé de compte c''est ?', NULL, 2, N'Le résumé de mes opérations bancaires', N'Le document indiquant mes coordonnées bancaires', N'Un document à fournir aux impôts', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (64, 2, 2, N'En finance, acheter une action c''est  ?', NULL, 2, N'Réparer une erreur comptable', N'Acheter une part de la dette de l''Etat', N'Investir dans le capital d''une entreprise', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (65, 2, 2, N'En finance, acheter une obligation, c''est ?', NULL, 2, N'Payer un salaire', N'Acheter une part de dette', N'Effectuer des virements réguliers', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (66, 2, 2, N'Que veut dire faire opposition ?', NULL, 2, N'Refuser une ouverture de compte', N'Répondre par courrier recommandé', N'Demander à sa banque le blocage de sa carte', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (67, 2, 2, N'A quel âge peut on ouvrir un Livret Jeune ?', NULL, 2, N'16 ans', N'12 ans', N'18 ans', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (69, 2, 2, N'Un placement disponible peut ?', NULL, 2, N'Être souscrit les jours ouvrés', N'Être retiré et utilisé quand on veut', N'Être consulté sans code confidentiel', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (70, 2, 2, N'Un compte rémunéré... ?', NULL, 2, N'Rapporte des intérêts', N'Est libellé en devise étrangère', N'Est une forme de crédit', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (72, 2, 2, N'Le « phishing » est une fraude …?', NULL, 2, N'Pour obtenir vos données personnelles', N'Pour pêcher dans des eaux interdites', N'Pour maquiller son CV', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (73, 2, 2, N'C''est quoi un indice boursier ?', NULL, 2, N'La preuve d''un délit d''initié', N'Un indicateur de performance', N'Une information pour un épargnant', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (74, 2, 2, N'Que faut-il faire avec sa carte bancaire ?', NULL, 2, N'La prêter à son meilleur ami', N'Apprendre son code par cœur', N'Ecrire le code pour ne pas l''oublier', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (75, 2, 2, N'Le découvert bancaire c’est … ?', NULL, 2, N'Un bonus pour les clients fidèles', N'Un droit pour les moins de 18 ans', N'Une forme de crédit', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (77, 2, 2, N'A partir de quel âge peut-on ouvrir un Livret A ?', NULL, 2, N'Dès la naissance ', N'12 ans ', N'18 ans', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (78, 2, 2, N'Le paiement sans contact chez un commerçant est possible jusqu''à ?', NULL, 2, N'150', N'Sans limite', N'50', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (79, 2, 2, N'Qu''est ce qu''un créancier ? ', NULL, 2, N'Une personne à qui je dois de l''argent', N'Un faux monnayeur', N'Une personne qui me doit de l''argent', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (80, 2, 2, N'Qu''est ce qu''un débiteur ?', NULL, 2, N'Une personne à qui je dois de l''argent ', N'Un distributeur de billets ', N'Une personne qui me doit de l''argent', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (81, 2, 2, N'Qu''est-ce que le solde bancaire ?', NULL, 2, N'Un compte sans frais ni commission ', N'La différence entre épargne et crédit', N'La différence entre ressources et dépenses', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (82, 2, 2, N'Qu''est-ce qu''un taux de change ?', NULL, 2, N'Le prix d''une monnaie dans une autre', N'Le taux d''évolution du chômage', N'La variation des prix dans le temps', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (83, 2, 2, N'Comment commence l''adresse d''un site sécurisé pour les paiements en ligne ?', NULL, 2, N'https', N'www.secure system', N'secure.http', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (84, 2, 2, N'Que signifie le sigle RIB ? ', NULL, 2, N'Relevé informatique bancaire', N'Relevé d''Information Bancaire', N'Relevé d''Identité Bancaire', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (85, 2, 2, N'Je loue un appartement, je dois l''assurer ?', NULL, 2, N'Oui', N'Non', NULL, 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (86, 2, 2, N'Comment s''appellent les revenus tirés d''une action  ?', NULL, 2, N'Les dividendes', N'Les intérêts', N'Les bonus', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (87, 2, 2, N'Un délit d''initié, c''est  acheter des titres ?', NULL, 2, N'A la hausse', N'A la baisse', N'A partir d''une information secrète', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (88, 2, 2, N'Que signifie le sigle ISR  ?', NULL, 2, N'Investissement super rentable', N'Investissement socialement responsable', N'Information sur les revenus', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (89, 2, 3, N'Quand a été créée la Banque de France ?', NULL, 3, N'1800', N'1870', N'1945', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (90, 2, 3, N'Que sont les agios ?', NULL, 3, N'Des pièces de monnaie espagnoles', N'Des frais bancaires', N'Des légumes', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (91, 2, 3, N'Qu’est-ce qu’un pécule ? ', NULL, 3, N'Une somme d’argent économisée', N'Un jeu de boules', N'Un récipient', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (92, 2, 3, N'En finance, que veut dire le sigle OPA ?', NULL, 3, N'Opération par apport', N'Offre publique d''achat', N'Ouverture par anticipation', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (93, 2, 3, N'Qui a inventé la carte à mémoire ?', NULL, 3, N'Roland Moréno', N'IBM', N'APPLE', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (94, 2, 3, N'C''est quoi l''échéance d''un prêt ?', NULL, 3, N'Le montant total', N'Le taux d''intérêt assurance comprise', N'La date de fin de remboursement', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (96, 2, 3, N'Le montant des intérêts d''un livret d''épargne c''est ?', NULL, 3, N'Le gain annuel de l''argent déposé', N'Les frais perçus par la banque ', N'La somme maximale que l''on peut déposer', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (97, 2, 3, N'Le safran est aussi cher que ?', NULL, 3, N'La truffe', N'La mandragore', N'L''or', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (99, 2, 3, N'Se porter caution c''est ?', NULL, 3, N'Le considérer comme un ami', N'S''engager à payer ses dettes', N'Prendre une position en Bourse', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (100, 2, 3, N'Quelle est la durée de validité d''un chèque ?', NULL, 3, N'1 an et 8 jours', N'1 mois et 8 jours', N'8 jours', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (104, 2, 3, N'Quel établissement assure des missions d''intérêt général ?', NULL, 3, N'La Caisse des Dépôts et Consignations', N'La Caisse Générale du Commerce et de l''Industrie', N'La Banque Générale', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (105, 2, 3, N'Qu''est il interdit de placer dans une coffre-fort ?', NULL, 3, N'Des denrées alimentaires périssables', N'Des bijoux', N'Des billets de banque', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (106, 2, 3, N'Dans l''assurance, lors d''un sinistre (feu, accident…) la franchise c''est ?', NULL, 3, N'Ce qui reste à la charge de l''assureur', N'Ce qui est remboursé par l''assureur', N'Ce qui reste à la charge de l''assuré', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (107, 2, 3, N'Le taux d''un prêt à taux variable varie en fonction ?', NULL, 3, N'Du remboursement déjà effectué', N'Du montant restant à rembourser', N'De la variation des marchés financiers', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (108, 2, 3, N'En finance, que veut dire faire défaut ?', NULL, 3, N'Créer de la fausse monnaie', N'Ne pas rembourser son crédit', N'Signer des chèques en bois', 2)
GO
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (109, 2, 3, N'Pièces et billets, c''est la monnaie fiduciaire. Les comptes bancaires c''est ?', NULL, 3, N'La monnaie bancaire', N'La monnaie scripturale', N'La masse monétaire', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (110, 2, 3, N'L''assurance d''une automobile ou d''une moto est obligatoire ? ', NULL, 3, N'Non', N'Oui', NULL, 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (111, 3, 1, N'La valeur d''un billet de 20 € est inférieure à ?', NULL, 1, N'30 pièces de 50 cts', N'17 pièces de 1 €', N'11 pièces de 2 €', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (112, 3, 1, N'J''ai 1 billet de 20 € et 12 pièces de 50 cts soit ?', NULL, 1, N'26', N'28', N'32', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (113, 3, 1, N'100 € équivalent à ?', NULL, 1, N'1 billet de 50 € et 30 pièces de 2 €', N'4 billets de 20 € et 3 billets de 5 €', N'4 billets de 20 € et 20 pièces de 1 euro', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (114, 3, 1, N'J’ai 20 pièces de 5 cts, 10 de 50 cts et une de 1 euro, soit ?', NULL, 1, N'5', N'7', N'16', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (115, 3, 1, N'Si j’achète 3 pains à 1,60 € chacun, cela me coûte ?', NULL, 1, N'3,8', N'4, 80 €', N'5,2', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (116, 3, 1, N'3 kilos de fraises coûtent 6,90 €. Un kilo coûte ?', NULL, 1, N'2,3', N'3,2', N'3,3', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (117, 3, 1, N'Mon menu coûte 20 €. J’ai 4 billets de 10 €, donc j’en utilise ?', NULL, 1, N'1', N'2', N'3', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (118, 3, 1, N'Je prête 30 € à un ami. Il me rend 20 €, il me doit encore ?', NULL, 1, N'20', N'10', N'15', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (119, 3, 1, N'J’ai gagné 417 € mais ai dépensé 205 €. Il me reste ?', NULL, 1, N'212', N'112', N'12', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (120, 3, 1, N'Isa gagnait 1000 € par mois. Depuis, elle gagne 2000 €, soit ?', NULL, 1, N'Autant qu’avant', N'2 fois moins qu’avant', N'2 fois plus qu’avant', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (121, 3, 1, N'100 € donneront 102 € dans un an. 300 € donneront dans un an ?', NULL, 1, N'102', N'306', N'300', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (122, 3, 1, N'Un billet de 10 € vaut plus que ?', NULL, 1, N'4 pièces de 2 €', N'11 pièces de 1 €', N'22 pièces de 50 cts', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (123, 3, 1, N'La monnaie étrangère vaut 0,1 €. Je change 100 €. Je reçois… ?', NULL, 1, N'110 unités', N'10 unités', N'1000 unités', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (124, 3, 2, N'Combien coûte un vêtement de 90 € soldé à 30 % ?', NULL, 2, N'63', N'60', N'27', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (126, 3, 2, N'Ma banque rémunère mes 100 € à 2,5 % et me prend 1 € de frais. A la fin de l''année j''ai ?', NULL, 2, N'101,5', N'102,5', N'103,5', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (127, 3, 2, N'Un achat de 50 € avec un rabais de 20 % mis dans un sac qui coute 5 € me revient à ?', NULL, 2, N'45', N'44', N'40', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (128, 3, 2, N'Vaut-il mieux placer sur un an  ?', NULL, 2, N'100 € à 4 %', N'500 € à 0,8 %', N'Je gagne la même somme', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (129, 3, 2, N'Vous achetez une livre de bonbons à 12,80 € le kilo. Vous payez ? ', NULL, 2, N'12,8', N'6,4', N'6,8', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (130, 3, 2, N'Votre achat de 350 € est exonéré de TVA à 20 %. Sinon, vous l''auriez payé ?', NULL, 2, N'400', N'420', N'280', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (131, 3, 2, N'Vous placez sur 1 an 250 € au taux de 2 %, vous disposez en fin d''année de... ?', NULL, 2, N'252', N'500', N'255', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (132, 3, 2, N'J''achète 6 pommes à 40 cts l''une et 5 poires à 50 cts l''une. Combien je paie ?', NULL, 2, N'4,9', N'49', N'5', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (133, 3, 2, N'Payé 12 € de l''heure, le salaire d''une journée de 7 h et 15 mn est ?', NULL, 2, N'87', N'85,8', N'84', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (134, 3, 2, N'Vous prêtez 220 € et on vous en rend 231 un an plus tard. Quel est le taux d''intérêt ?', NULL, 2, N'0,11', N'0,05', N'0,1', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (135, 3, 2, N'Un lingot de 1kg contient 99,5 % d''or pur, soit ? ', NULL, 2, N'995 g d''or', N'1005 g d''or', N'1000 g d''or', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (136, 3, 2, N'J’ai 55,70 € et je dépense 14,90 €, il me reste ?', NULL, 2, N'40,8', N'30,8', N'40,9', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (137, 3, 3, N'J''ai un exemplaire de chaque billet, soit ?', NULL, 3, N'675', N'780', N'885', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (138, 3, 3, N'Un milliardaire possède au moins ?', NULL, 3, N'1 T€', N'1 G€', N'1 M€', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (139, 3, 3, N'Si on gagne 1 fois sur 4 au casino et qu''on joue 100 €, que va-t-il arriver ?', NULL, 3, N'On gagne 25 €', N'On ne sait pas, c''est un jeu de hasard', N'On perd 100 €', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (140, 3, 3, N'L''épaisseur de la pièce de 2 € est de 2,2 mm. Un tas de 240 € est haut de  ?', NULL, 3, N'26,4 cm', N'52,8 cm', N'48,0 cm', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (141, 3, 3, N'Un carat équivaut à 0,2 g. Et 5,4 carats ?', NULL, 3, N'10,8 g', N'10,8 dg', N'10,8 cg', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (142, 3, 3, N'J''ai perdu 20 %. Combien gagner pour revenir à ma somme initiale ?', NULL, 3, N'0,15', N'0,2', N'0,25', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (143, 3, 3, N'J''achète un ordinateur à 650 €. Je verse 200 € à l''achat et paie pendant dix mois ?', NULL, 3, N'65 € / mois', N'45 € / mois', N'25 € / mois', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (144, 3, 3, N'Si j''ai un exemplaire de chaque pièce en euro, combien ai-je d''euros ?', NULL, 3, N'4,21', N'10', N'3,88', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (145, 4, 1, N'Que signifie le sigle CDD ?', NULL, 1, N'Contrat à durée déterminée', N'Convention de défiscalisation directe', N'Concentration des dividendes distribués', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (148, 4, 1, N'Quand on est en télétravail, on travaille ?', NULL, 1, N'Pour une chaîne de télévision', N'Dans la sphère Internet', N'Temporairement à son domicile', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (150, 4, 1, N'Que signifie le sigle PME ?', NULL, 1, N'Prix moyen de l''énergie', N'Paiement en monnaie électronique', N'Petites et moyennes entreprises', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (151, 4, 1, N'Le bail est ?', NULL, 1, N'Un contrat d''achat de machine outil', N'Un contrat de longue durée', N'Un contrat de location', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (153, 4, 1, N'Qu''est ce que le pouvoir d''achat ?', NULL, 1, N'Ce que je peux m''offrir avec mes revenus', N'Le plafond de ma carte bancaire', N'Corrompre un fonctionnaire', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (156, 4, 1, N'Une dépense contrainte est  ? ', NULL, 1, N'Obligatoire', N'Minimale', N'Impulsive', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (157, 4, 1, N'L''achat d''un nouveau smartphone est une charge… ?', NULL, 1, N'Exceptionnelle', N'Contrainte', N'Courante', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (158, 4, 1, N'20 € gagnés avec un babysitting, c''est ?', NULL, 1, N'Un don', N'Une dépense', N'Une ressource', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (159, 4, 1, N'200 € payés pour un nouveau smartphone, c''est ?', NULL, 1, N'Une spéculation', N'Une dépense', N'Une ressource', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (160, 4, 2, N'Une importation, c''est un bien ou un service acheté à l''étranger ?', NULL, 2, N'Oui', N'Non', NULL, 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (161, 4, 2, N'Une exportation, c''est un bien ou un service vendu à l''étranger ?', NULL, 2, N'Non', N'Oui', NULL, 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (162, 4, 2, N'Qu''est-ce que l''inflation ?', NULL, 2, N'La hausse de la Bourse', N'La hausse généralisée des prix', N'La hausse des taux de rémunération de l''épargne', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (163, 4, 2, N'Que signifie le sigle TVA ?', NULL, 2, N'Taxe à la valeur ajoutée', N'Taux variable ajusté', N'Taux en valeurs actualisées', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (165, 4, 2, N'Que signifie le sigle PIB ?', NULL, 2, N'Production industrielle brute', N'Performance individuelle brute', N'Produit intérieur brut', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (166, 4, 2, N'Qui a écrit "Le capital" ?', NULL, 2, N'Karl Marx', N'Nostradamus', N'Bill Gates', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (167, 4, 2, N'Qu''est-ce qu''un monopole ?', NULL, 2, N'Beaucoup d''offreurs pour un seul acheteur', N'Un seul offreur pour beaucoup d''acheteurs', N'Beaucoup d''offreurs pour beaucoup d''acheteurs', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (168, 4, 2, N'Qu''appelle-t-on vente aux enchères ?', NULL, 2, N'Vente sans intermédiaire', N'Vente à celui qui offre le prix le plus élevé', N'Vente sur Internet', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (171, 4, 2, N'L''épargne de précaution... ?', NULL, 2, N'Ne produit pas d''intérêts', N'Est placée en vue de la retraite', N'Est disponible au cas où…', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (172, 4, 2, N'Qu''est ce qui n''est pas une ressource fixe ?', NULL, 2, N'Le salaire', N'La vente d''un meuble dans une brocante', N'Les intérêts d''un livret A', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (173, 4, 2, N'Qu''est-ce qui ne permet pas de réduire ses dépenses ?', NULL, 2, N'Acheter en soldes', N'Acheter les objets vantés par la publicité', N'Vendre les objets inutilisés dans une brocante', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (174, 4, 3, N'Le secteur de l''agriculture, de la pêche et de la forêt est le secteur ?', NULL, 3, N'Secondaire', N'Tertiaire', N'Primaire', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (176, 4, 3, N'Quelles activités ne font pas partie du secteur tertiaire ?', NULL, 3, N'L''hôtellerie et la restauration', N'L''aéronautique et la construction navale', N'La communication et l''information', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (177, 4, 3, N'Le mécénat, c''est quoi ?', NULL, 3, N'Investissement dans l''agriculture', N'Soutien financier sans contrepartie', N'Réhabilitation des personnes condamnées à tort', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (179, 4, 3, N'Une association à but non lucratif... ?', NULL, 3, N'Ne distribue pas de bénéfices à ses membres', N'N''achète pas de produits de luxe', N'N''a pas de salariés', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (181, 4, 3, N'Que veut dire salaire net ?', NULL, 3, N'Sans les cotisations sociales', N'Pas touché au "black"', N'Annuel, primes incluses', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (183, 4, 3, N'Le commerce équitable permet de ?', NULL, 3, N'Rémunérer correctement les producteurs', N'Taxer les gros pollueurs', N'Eviter l''abattoir aux chevaux âgés', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (184, 4, 3, N'Quel type de formation permet d''avoir un salaire ?', NULL, 3, N'L''apprentissage', N'Les classes préparatoires', N'L''année sabbatique', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (185, 5, 1, N'Sur la face française des pièces de 1 et 2 €, il y a :', NULL, 1, N'Un arbre', N' L’arc de Triomphe', N'La tour Eiffel', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (186, 5, 1, N'Avant l''euro, la monnaie française était ?', NULL, 1, N'L''écu', N'Le franc', N'Le louis d''or', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (187, 5, 1, N'Lequel de ces pays n’utilise pas l’euro ?', NULL, 1, N'L’Allemagne', N'La Suisse', N'L''Espagne', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (188, 5, 1, N'Combien existe-t-il de pièces en euros ?', NULL, 1, N'3', N'5', N'8', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (189, 5, 1, N'Que trouve-t-on sur toutes les pièces en euros ?', NULL, 1, N'Monnet, le père de l’Europe', N'Marianne', N'Une carte de l’Europe', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (190, 5, 1, N'Quand sont apparues les pièces en euros ?', NULL, 1, N'En 1992', N'En 1998', N'En  2002', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (191, 5, 1, N'Parmi ces trois monnaies, laquelle n’est plus utilisée ?', NULL, 1, N'Le franc suisse', N'L''euro', N'Le mark', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (192, 5, 1, N'De quelle couleur est le billet de 20 € ?', NULL, 1, N'Jaune', N'Bleu', N'Vert', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (193, 5, 1, N'Quelle monnaie n’a pas été remplacée par l’euro ?', NULL, 1, N'Le franc luxembourgeois', N'La livre sterling', N'La lire italienne', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (194, 5, 1, N'Quel billet d’euro est vert ?', NULL, 1, N'Le billet de 100 €', N'Le billet de 50 €', N'Le billet de 20 €', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (195, 5, 1, N'Combien existent-ils de pièces cuivrées en euros ?', NULL, 1, N'1', N'3', N'5', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (196, 5, 2, N'L''euro  est la monnaie d''une partie de l''Europe, continent qui s''étend ?', NULL, 2, N'De Lisbonne à Moscou', N'De l''Atlantique à l''Oural', N'De l''Irlande à l''Ukraine', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (197, 5, 2, N'La pièce de 10 cts a un diamètre...?', NULL, 2, N'Inférieur à celle de 5 cts', N'Supérieur à celle de 5 cts', N'Identique à celle de 5 cts', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (198, 5, 2, N'A quoi servent les points en relief sur les billets ?', NULL, 2, N'A les compter pour les banquiers', N'A les reconnaître pour les aveugles', N'A les décoller lors de la fabrication', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (199, 5, 2, N'Quel billet en euro n''est plus émis depuis 2018 ?', NULL, 2, N'Le billet de 500 €', N'Le billet de 1000 €', N'Le billet de 5 €', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (200, 5, 2, N'Combien existe-t-il de billets en euros ?', NULL, 2, N'3', N'7', N'10', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (201, 5, 3, N'En quelle année a été créée la zone euro ?', NULL, 3, N'1999', N'2001', N'2012', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (202, 5, 3, N'Que symbolisent les ponts sur les billets en euros ?', NULL, 3, N'L’union', N' La découverte', N'L’histoire', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (203, 5, 3, N'Que symbolisent les portes sur les billets en euros ?', NULL, 3, N'L’ouverture', N'La paix', N' La liberté', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (204, 5, 3, N'Où a été signé le traité créant le "Marché commun" en 1957 ?', NULL, 3, N'Maastricht', N'Rome', N'Luxembourg', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (205, 5, 3, N'C''est quoi le filigrane d''un billet ?', NULL, 3, N'La signature de l''émetteur', N'Le pourtour', N'L''image en transparence', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (206, 5, 3, N'Où sont frappées les pièces en euro françaises ?', NULL, 3, N'A Paris (75)', N'A Chamalières (63)', N'A Pessac (33)', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (207, 5, 3, N'Avant l''euro, qu''est-ce qui n''a jamais été la monnaie française ?', NULL, 3, N'La piastre', N'Le franc', N'La livre', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (208, 5, 3, N'L''Europe envisage de créer un euro numérique, c''est quoi ?', NULL, 3, N'Pour payer son équipement informatique', N'Une crypto-monnaie', N'Pour les échanges de monnaie entre banques', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (209, 5, 3, N'Quelle monnaie n''a jamais existé ?', NULL, 3, N'Le ramdam', N'Le sucre', N'L''obole', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (210, 5, 3, N'En France, on n''a jamais payé en ?', NULL, 3, N'Denier', N'Drachme', N'Ecu', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (211, 5, 3, N'Qui a inventé le papier monnaie ?', NULL, 3, N'Johannes Gutenberg', N'Les Egyptiens', N'Les Chinois', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (212, 5, 3, N'Quelle monnaie n''a pas disparu à la création de l''euro ?', NULL, 3, N'Le florin néerlandais', N'Le franc Pacifique', N'La peseta', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (213, 5, 3, N'Une monnaie commune évite ?', NULL, 3, N'Les frais  de change', N'La guerre commerciale', N'Une fiscalité trop lourde', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (214, 5, 3, N'Quelle monnaie utilise-t-on en Andorre ?', NULL, 3, N'Le franc CFA', N'L''euro', N'L''andorran', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (215, 5, 3, N'Qu''a l''euro de plus qu''une crypto-monnaie ?', NULL, 3, N'Il est plus beau', N'Il est plus cher', N'Il a cours légal', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (216, 5, 3, N'Une monnaie ne permet pas de … ?', NULL, 3, N'Echanger', N'Blanchir', N'Conserver', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (217, 6, 1, N'Que signifie « mettre de l’argent de côté »  ?', NULL, 1, N'Dépenser', N'Emprunter', N'Épargner', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (218, 6, 1, N'Que signifie « jeter l’argent par les fenêtres » ?', NULL, 1, N'Dépenser son argent sans compter', N'Déposer de l’argent en banque', N'Acheter des rideaux', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (219, 6, 1, N'Que signifie « mettre de l''argent de côté » ?', NULL, 1, N'Voler de l’argent', N'Cacher de l''argent', N'Epargner', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (220, 6, 1, N'Que signifie « payer en liquide » ?', NULL, 1, N'Payer des boissons', N'Payer en pièces et en billets', N'Payer par carte bancaire', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (221, 6, 1, N'Que signifie : « jeter l''argent par les fenêtres » ?', NULL, 1, N'Faire isoler les fenêtres de la maison', N'Dépenser déraisonnablement', N'Acheter sur Internet', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (223, 6, 1, N'Que signifie : « se faire plumer » ?', NULL, 1, N'Se faire escroquer', N'Enfiler un costume de cérémonie', N'Perdre ses cheveux', 1)
GO
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (224, 6, 1, N'Que signifie : « fêter ses noces d''or » ?', NULL, 1, N'Déballer les cadeaux de mariage', N'Se faire une donation entre époux', N'Avoir été mariés pendant 50 ans', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (225, 6, 1, N'On la dit voleuse, il s''agit de ?', NULL, 1, N'La pie', N'La salamandre', N'La mite', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (226, 6, 1, N'Que signifie : « avoir un cœur d''or » ?', NULL, 1, N'Avoir une pile cardiaque aux ions d''or', N'Être dur en affaires', N'Être bon et généreux', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (227, 6, 2, N'Que signifie « rendre la monnaie de sa pièce » ?', NULL, 2, N'Rembourser quelqu’un', N'Se battre avec une pièce de monnaie', N'Se venger', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (228, 6, 2, N'Que signifie « consommer à l’œil » ?', NULL, 2, N'Acheter des lunettes de soleil', N'Manger des yeux de poisson', N'Consommer gratuitement', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (229, 6, 2, N'Que signifie « être sur la paille » ?', NULL, 2, N'Avoir un bon matelas', N'Être ruiné', N'Dormir à l''écurie', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (230, 6, 2, N'Que signifie « faire un chèque en bois » ?', NULL, 2, N'Payer sans avoir d’argent', N'Construire un meuble', N'Se promener dans les bois', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (231, 6, 2, N'Que signifie « être dans le rouge »?', NULL, 2, N'Avoir dépensé plus que ses ressources', N'Avoir pris un coup de soleil', N'Avoir la rougeole', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (232, 6, 2, N'Que signifie : « mettre la clé sous la porte » ?', NULL, 2, N'Cacher les clés sous le paillasson', N'Faire faillite pour une entreprise', N'Avoir monté les gonds de la porte à l''envers', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (233, 6, 2, N'Que signifie : « graisser la patte » ?', NULL, 2, N'Nourrir un oiseau', N'Faire frire une cuisse de canard', N'Corrompre une personne', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (234, 6, 2, N'Que signifie : « vouloir le beurre et l’argent du beurre » ?', NULL, 2, N'Mélanger du beurre et de l''eau', N'Faire une demande exagérée', N'Faire des études de crémier', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (235, 6, 2, N'Que signifie : « faire un pont d''or » ?', NULL, 2, N'Acheter une bague de fiançailles', N'Dormir pendant le week-end', N'Faire une offre très intéressante', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (236, 6, 2, N'Au jeu, que signifie : «intéresser la partie » ?', NULL, 2, N'Miser de l''argent', N'Autoriser les spectateurs', N'Changer la règle du jeu', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (237, 6, 2, N'Que signifie : « un enfant prodigue » ?', NULL, 2, N'Une personne qui dilapide son argent', N'Un génie en herbe', N'Une créature de jeu vidéo', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (238, 6, 2, N'Que signifie : « être fauché comme les blés » ?', NULL, 2, N'Être chauve', N'Avoir été pris dans une fusillade', N'Être pauvre', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (239, 6, 2, N'Que signifie : « être en compte avec quelqu''un » ?', NULL, 2, N'Monter une affaire avec lui', N'Lui en vouloir', N'Lui devoir de l''argent ou qu''il vous en doive', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (240, 6, 2, N'Que signifie : « mettre la main à la poche » ?', NULL, 2, N'Payer', N'Voler', N'Epargner', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (241, 6, 2, N'Que signifie : « être un panier percé » ?', NULL, 2, N'Rêver en classe', N'Dilapider son argent', N'Perdre ses clés', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (242, 6, 2, N'J''ai «l''argent qui me brûle les doigts », je suis ?', NULL, 2, N'Econome', N'Dépensier', N'Banquier', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (244, 6, 3, N'Que signifie « être plein aux as » ?', NULL, 3, N'Être chanceux', N'Avoir trop dépensé', N'Être très riche', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (245, 6, 3, N'Que signifie « prendre pour argent comptant » ?', NULL, 3, N'Avoir de l’argent sur son compte', N'Croire naïvement quelqu’un', N'Retirer de l’argent', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (246, 6, 3, N'Que signifie « payer en monnaie de singe » ?', NULL, 3, N'Payer dans une monnaie qui n’a pas de valeur', N'Utiliser une monnaie ancienne', N'Faire du troc', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (247, 6, 3, N'Que signifie « payer en espèces sonnantes et trébuchantes » ?', NULL, 3, N'Payer en faisant sonner des pièces de monnaie', N'Trébucher sur des pièces de monnaie', N'Payer avec des  pièces et des billets', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (248, 6, 3, N'Que signifie « aux frais de la princesse » ?', NULL, 3, N'Avoir été invité à dîner par une princesse', N'Obtenir quelque chose gratuitement', N'Se marier avec une princesse', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (249, 6, 3, N'Que signifie « coûter les yeux de la tête » ?', NULL, 3, N'Coûter peu cher', N'Coûter très cher', N'Au meilleur prix', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (250, 6, 3, N'Que signifie « avoir des oursins dans les poches » ? ', NULL, 3, N'Pêcher des oursins', N'Aimer les animaux', N'Être radin', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (251, 6, 3, N'Que signifie « toucher le pactole » ?', NULL, 3, N'Recevoir beaucoup d’argent', N'Dépenser sans limites', N'Ne pas avoir de chance', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (252, 6, 3, N'Que signifie « tirer le diable par la queue » ?', NULL, 3, N'Être insolent', N'Manquer d''argent', N'S''amuser avec son animal', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (253, 6, 3, N'Que signifie « blanchir de l’argent » ?', NULL, 3, N'Nettoyer les pièces', N'Compter son argent', N'Changer de l’argent illégal en argent légal ', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (255, 6, 3, N'Qui a dit : « l''argent n''a pas d''odeur » ?', NULL, 3, N'Le bandit américain Al Capone', N'Le parfumeur inventeur de l''eau de Cologne', N'L''empereur romain Vespasien', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (256, 6, 3, N'Que signifie : « tenir les cordons de la bourse » ?', NULL, 3, N'Gérer le budget familial', N'Fermer son porte-monnaie', N'Recevoir un héritage', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (257, 6, 3, N'Que signifie : « des comptes d''apothicaire » ?', NULL, 3, N'Espérer une rentrée d''argent', N'Réaliser des calculs très précis', N'Contester une facture', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (258, 6, 3, N'Que signifie : « en avoir pour son argent » ?', NULL, 3, N'Être satisfait de ce qu''on a eu pour le prix payé', N'Vouloir voler une personne', N'Avoir été roulé', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (259, 6, 3, N'Que signifie : «juger sur pièces » ?', NULL, 3, N'Examiner des informations objectives', N'Goûter un tonneau de vin', N'Vérifier la teneur en métal d''une pièce de monnaie', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (260, 6, 3, N'Qui est  « un bon serviteur mais un mauvais maître » ?', NULL, 3, N'Le banquier', N'L''argent', N'Le boursier', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (261, 6, 3, N'Que signifie : « dîner à la fortune du pot » ?', NULL, 3, N'Manger une poule au pot', N'Manger beaucoup', N'Invité à l''improviste', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (262, 6, 3, N'Que signifie : « faire des dépenses somptuaires » ?', NULL, 3, N'Embellir son appartement', N'Engager des frais excessifs', N'Payer un entrepreneur', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (263, 6, 3, N'Que signifie : « être chocolat » ?', NULL, 3, N'S''être fait avoir', N'Être grassouillet', N'Avoir trop bronzé', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (264, 7, 1, N'Quel est le premier système d’échange de marchandises ?', NULL, 1, N'Le truc', N'Le troc', N'Le tic-tac', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (265, 7, 1, N'Qui était Crésus ?', NULL, 1, N'Un roi de Lydie qui a inventé la monnaie en or ', N'Un riche marchand grec', N'Le créateur d’un jeu vidéo', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (266, 7, 1, N'Qui a composé « l’Ode à la joie », l’hymne européen ?', NULL, 1, N'Beethoven', N'Mozart', N'Vivaldi', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (267, 7, 1, N'Le drapeau européen comporte ?', NULL, 1, N'6 étoiles', N'12 étoiles', N'27 étoiles', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (268, 7, 1, N'Qui a écrit  « L’Avare » ? ', NULL, 1, N'Jean de la Fontaine', N'Jacques Prévert', N'Molière', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (269, 7, 1, N'Picsou est un personnage créé par ?', NULL, 1, N'Walt Disney', N'Uderzo', N'Hergé', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (270, 7, 1, N'Dans quelle monnaie Jules César payait-il  ses soldats ?', NULL, 1, N'Sesterce', N'Lire', N'Pilum', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (271, 7, 1, N'Le masque de Toutankhamon est en... ?', NULL, 1, N'Argent ', N'Or', N'Platine', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (272, 7, 1, N'Dans quel conte un âne "pond" des pièces d''or ?', NULL, 1, N'Peau d''âne', N'Les mémoires d''un âne', N'L''âne culotte', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (273, 7, 1, N'Avec quoi les Chinois du 16ème siècle faisaient-ils leurs comptes ?', NULL, 1, N'Une clepsydre', N'Un boulier', N'Des buchettes', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (274, 7, 1, N'Dans la fable de La Fontaine,  la cigale ?', NULL, 1, N'Epargne', N'Est dépensière', N'Ne sait pas chanter', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (275, 7, 1, N'Quelle est la suite du "Secret de la Licorne" pour Tintin ?', NULL, 1, N'Le sceptre d''Ottokar', N'Le trésor de Rackham le rouge', N'Les bijoux de la Castafiore', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (276, 7, 1, N'Qui a trouvé le trésor des 40 voleurs ?', NULL, 1, N'Barberousse', N'Aladin', N'Ali Baba', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (277, 7, 1, N'Au Monopoly, comment s''appelle le maître du jeu ?', NULL, 1, N'La banque', N'Merlin', N'Trust', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (278, 7, 1, N'En quoi est constitué le "Magot des Dalton" ?', NULL, 1, N'En or volé à la banque de Red Rock Junction', N'En faux billets de 3 dollars', N'La paie des gardiens de la prison', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (279, 7, 1, N'Qui a écrit "La fortune de Gaspard"', NULL, 1, N'Jonathan Swift', N'La comtesse de Ségur', N'Honoré de Balzac', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (280, 7, 1, N'Dans quel album Astérix se cache dans un coffre-fort ?', NULL, 1, N'Chez les Helvètes', N'Le chaudron', N'L''Odyssée d''Obélix', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (281, 7, 1, N'De qui est le film « La ruée vers l''or »  ?', NULL, 1, N'Steven Spielberg', N'Charlie Chaplin', N'François Truffaut', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (282, 7, 2, N'Qu''elle était probablement la 1ère monnaie ?', NULL, 2, N' Des coquillages', N'Des objets fabriqués', N' Des pièces d’or', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (283, 7, 2, N'Europe était ?', NULL, 2, N'Une princesse de la mythologie grecque', N'Un monument historique', N'Une femme politique', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (284, 7, 2, N'On parle de « la crise de 1929 » pour désigner ?', NULL, 2, N'Un conflit entre plusieurs pays', N'Une crise financière', N'Un film muet', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (285, 7, 2, N'Quand est célébrée la journée de l''Europe ?', NULL, 2, N'Le 1er mai', N'Le 9 mai', N'Le 11 novembre', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (286, 7, 2, N'Qui a écrit  « L''ile au trésor » ? ', NULL, 2, N'Robert Louis Stevenson', N'Enid Blyton', N'Casimir', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (287, 7, 2, N'Dans quelle fable de La Fontaine le travail est un trésor ?', NULL, 2, N'La laitière et le pot au lait', N'Le chat, la belette et le petit lapin', N'Le laboureur et ses enfants', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (288, 7, 2, N'Que cherchaient les conquistadors en Amazonie ?', NULL, 2, N'Le jaguar', N'Le fleuve Amazone', N'L''Eldorado', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (289, 7, 2, N'Pour Harry Potter, quelle monnaie est en bronze ?', NULL, 2, N'La noise', N'La mornille', N'Le gallion', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (290, 7, 2, N'Que cherchaient Jason et les Argonautes ?', NULL, 2, N'La toison d''or', N'La peau du lion de Némée', N'Le Graal', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (291, 7, 2, N'Comment s''appelait l''impôt sur le sel ?', NULL, 2, N'La gabelle', N'La saline', N'La dîme', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (292, 7, 2, N'Qui transformait tout ce qu''il touchait en or ?', NULL, 2, N'Le dieu Héphaïstos', N'L''empereur Marc-Aurèle', N'Le roi Midas', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (293, 7, 2, N'Qui voulait transformer le plomb en or ?', NULL, 2, N'Les orpailleurs', N'Les courtiers', N'Les alchimistes', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (294, 7, 2, N'Quel est le nom de la famille de grands banquiers florentins ?', NULL, 2, N'Les Colonna', N'Les Médicis', N'Les Sforza', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (295, 7, 2, N'A qui Pâris a-t-il donné la pomme d''or de la plus belle ?', NULL, 2, N'Hélène de Troie', N'Cléopâtre', N'Aphrodite', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (296, 7, 3, N'Quel roi figure sur le premier franc ?', NULL, 3, N'Charlemagne', N'Jean II Le Bon', N'Louis IX', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (297, 7, 3, N'Quelle est l’origine du mot « salaire » ?', NULL, 3, N'Le poivre', N'La salade', N'Le sel', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (298, 7, 3, N'Le traité de Rome créant l’Union européenne a été signé en ?', NULL, 3, N'1945', N'1957', N'1962', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (299, 7, 3, N'Quelle est la devise de l’Union européenne ?', NULL, 3, N'« Unies dans la diversité »', N'« Ensemble pour changer »', N'« Regroupés pour mieux régner »', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (300, 7, 3, N'On parle de la « bulle Internet » pour désigner ?', NULL, 3, N'Une crise financière des années 2000', N'Un film', N'La naissance d’Internet', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (301, 7, 3, N'Qui a écrit le roman « L’argent » ? ', NULL, 3, N'Molière', N'La comtesse de Ségur', N'Emile Zola', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (302, 7, 3, N'Qui a créé le louis d''or ?', NULL, 3, N'François 1er', N'Louis XIII', N'Louis XIV', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (303, 7, 3, N'En France, la première Bourse est apparue à ?', NULL, 3, N'Paris', N'Toulouse', N'Bordeaux', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (304, 7, 3, N'La première banque est apparue ?', NULL, 3, N'Au Moyen-âge', N'Dans l''Antiquité', N'À la Renaissance', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (305, 7, 3, N'Qu''est-ce que le « Système de Law » ? ', NULL, 3, N'Le code monétaire en Grande-Bretagne', N'Une arnaque financière au XVIIIème siècle', N'Une astuce pour gagner au casino', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (306, 7, 3, N'Lesquels de ces frères sont des banquiers et investisseurs du XIXème siècle ?', NULL, 3, N'Les frères Grimm', N'Les frères Pereire', N'Les frères Dardenne', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (307, 7, 3, N'En quoi étaient payés les biens nationaux à la Révolution ?', NULL, 3, N'En blé', N'En litres de vin (ancêtres des "pots de vin")', N'En assignats, monnaie papier', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (308, 7, 3, N'"Monnaie de singe" (Monkey Business en vo) est un film avec ?', NULL, 3, N'Georges Méliès', N'Laurel et Hardy', N'Les Marx Brothers', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (309, 7, 3, N'Qui était Alexandre Brongniart sous Napoléon 1er ?', NULL, 3, N'Le ministre des finances', N'L''architecte du palais de la Bourse à Paris', N'Le meilleur soldat de la Grande Armée', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (311, 7, 3, N'Originaire de Bourges, il a financé son roi. Qui est-ce ?', NULL, 3, N'André Chénier', N'Philippe de Commynes', N'Jacques Cœur', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (312, 7, 3, N'Au Moyen-Age, qui a inventé l''une des 1ères monnaies scripturales  ?', NULL, 3, N'Les marchands de Bruges', N'Les banquiers lombards', N'Les Cathares', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (313, 7, 3, N'On cherche toujours leur trésor. Qui sont-ils ?', NULL, 3, N'Les corsaires malouins', N'Les druides', N'Les templiers', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (314, 7, 3, N'Qui est Shylock dans « Le Marchand de Venise » de Shakespeare ?', NULL, 3, N'Un capitaine de bateau', N'Un usurier', N'Un géôlier', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (315, 7, 3, N'Qui prélevait les impôts avant la Révolution ?', NULL, 3, N'Le gabelou', N'Le fermier général', N'Le sénéchal', 2)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (316, 7, 3, N'Le creusement de ce canal a causé une grande arnaque financière ?', NULL, 3, N'Canal de Panama', N'Canal de Suez', N'Canal du Midi', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (317, 7, 3, N'Qui peut voter au suffrage censitaire ?', NULL, 3, N'Ceux qui paient des impôts', N'Ceux qui ont fait des études supérieures', N'Ceux qui habitent au centre-ville', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (318, 7, 3, N'Une des premières bulles spéculatives concernait ?', NULL, 3, N'La porcelaine', N'Le savon', N'Les oignons de tulipe', 3)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (319, 7, 3, N'Grand argentier, il fut arrêté par d''Artagnan. Qui est-ce ?', NULL, 3, N'Nicolas Fouquet', N'Jean-Baptiste Colbert', N'Sébastien de Vauban', 1)
INSERT [dbo].[question] ([id], [id_theme], [difficulty], [question], [image], [value], [texteR1], [texteR2], [texteR3], [correct_answer]) VALUES (320, 7, 3, N'Qui a composé le tube «Money» ?', NULL, 3, N'Lady Gaga', N'Pink Floyd', N'Amy Winehouse', 2)
SET IDENTITY_INSERT [dbo].[question] OFF
GO
INSERT [dbo].[theme] ([id], [val]) VALUES (1, N'anglais')
INSERT [dbo].[theme] ([id], [val]) VALUES (2, N'banque')
INSERT [dbo].[theme] ([id], [val]) VALUES (3, N'calcul mental')
INSERT [dbo].[theme] ([id], [val]) VALUES (4, N'economie')
INSERT [dbo].[theme] ([id], [val]) VALUES (5, N'euro')
INSERT [dbo].[theme] ([id], [val]) VALUES (6, N'expressions')
INSERT [dbo].[theme] ([id], [val]) VALUES (7, N'histoire')
GO
ALTER TABLE [dbo].[question]  WITH CHECK ADD  CONSTRAINT [FK_question_theme] FOREIGN KEY([id_theme])
REFERENCES [dbo].[theme] ([id])
GO
ALTER TABLE [dbo].[question] CHECK CONSTRAINT [FK_question_theme]
GO
USE [master]
GO
ALTER DATABASE [SuperEuro] SET  READ_WRITE 
GO
